const { Shop } = require('../models');

const shopData = [
  {
      shop_name: "ZR51 Performance",
      address: "5612 E Alameda Ct",
      city: "Cave Creek",
      shop_state: "Arizona",
      zip: 85331,
      phone: 6023196575,
      state_id: 2,
  },
  {
      shop_name: "Larrys Engine & Marine",
      address: "600 W Lester",
      city: "Tucson",
      shop_state: "Arizona",
      zip: 85705,
      phone: 5206235373,
      state_id: 2,
  },
  {
      shop_name: "Pfaff Engine Builders",
      address: "5362 System Drive",
      city: "Huntington Beach",
      shop_state: "California",
      zip: 92649,
      phone: 7148992311,
      state_id: 4,
  },
  {
      shop_name: "Jerry Price",
      address: "3160 N Industrial Way",
      city: "Castlerock",
      shop_state: "Colorado",
      zip: 80104,
      phone: 3036215101,
      state_id: 5,
  },
  {
      shop_name: "Haibeck Automotive Technology",
      address: "430 W Kay Unit D",
      city: "Addison",
      shop_state: "Illinois",
      zip: 80104,
      phone: 3036215101,
      state_id: 11,
  },
  {
      shop_name: "Pepmeier Engine Development",
      address: "10298 Copper Ridge Drive",
      city: "Fishers",
      shop_state: "Indiana",
      zip: 46040,
      phone: 3175033287,
      state_id: 12,
  },
  {
      shop_name: "Graham Behan",
      address: "TBD",
      city: "New Concord",
      shop_state: "Kentucky",
      zip: 42076,
      phone: 2607018860,
      state_id: 15,
  },
  {
      shop_name: "Doug Rippie Motorsports",
      address: "412 Pacific Ave",
      city: "Waverly",
      shop_state: "Minnesota",
      zip: 55390,
      phone: 7636586109,
      state_id: 21,
  },
  {
      shop_name: "Crossed Flags Performance",
      address: "37007 Red Rock",
      city: "Magnolia",
      shop_state: "Texas",
      zip: 77355,
      phone: 8327481286,
      state_id: 41,
  },
  {
      shop_name: "JWC Performance",
      address: "605 Guilford Ave",
      city: "Chambersburg",
      shop_state: "Pennsylvania",
      zip: 17201,
      phone: 3019916991,
      state_id: 36,
  },
  {
      shop_name: "Evolution Motorsports",
      address: "88 Le Way Dr",
      city: "Fredericksburg",
      shop_state: "Virginia",
      zip: 22406,
      phone: 5407378779,
      state_id: 44,
  },
  {
      shop_name: "Benchmark Auto",
      address: "8248 NE SR 104",
      city: "Kingston",
      shop_state: "Washington",
      zip: 98036,
      phone: 3602976812,
      state_id: 45,
  },
  {
      shop_name: "Freedom Cars",
      address: "31 Cleveland Ave",
      city: "Nashville",
      shop_state: "Tennessee",
      zip: 37210,
      phone: 6152545252,
      state_id: 40,
  },
  {
      shop_name: "Brady's High Performance",
      address: "386 Millwood Rd.",
      city: "Willow Street",
      shop_state: "Pennsylvania",
      zip: 17584,
      phone: 7172830056,
      state_id: 36,
  },
  {
      shop_name: "Vette Doctors",
      address: "52 Elm Pl",
      city: "Amytyville",
      shop_state: "New York",
      zip: 11701,
      phone: 6318410779,
      state_id: 30,
  },
  {
      shop_name: "Pine Belt Chevrolet",
      address: "1088 RT-88",
      city: "Lakewood",
      shop_state: "New Jersey",
      zip: 08701,
      phone: 8883746323,
      state_id: 28,
  },
  {
      shop_name: "Banks Chevrolet",
      address: "137 Manchester St",
      city: "Concord",
      shop_state: "New Hampshire",
      zip: 03301,
      phone: 6033696657,
      state_id: 27,
  },
  {
      shop_name: "Eberts Engine Service",
      address: "3101 Patterson Dr",
      city: "New Orleans",
      shop_state: "Louisiana",
      zip: 70114,
      phone: 5045247681,
      state_id: 16,
  },
  {
      shop_name: "Franks Performance",
      address: "2020 S. Susan St",
      city: "Santa Ana",
      shop_state: "California",
      zip: 92704,
      phone: 7144035758,
      state_id: 4,
  },
  {
      shop_name: "Precision Motive",
      address: "25789 Dollar St",
      city: "Hayward",
      shop_state: "California",
      zip: 94544,
      phone: 5108860789,
      state_id: 4,
  },
  {
      shop_name: "Northstar Automotive",
      address: "3790 OH-3",
      city: "Sunbury",
      shop_state: "Ohio",
      zip: 43074,
      phone: 7409657525,
      state_id: 33,
  },
  {
      shop_name: "Purifoy Chevrolet",
      address: "601 Denver Ave",
      city: "Fort Lupton",
      shop_state: "Colorado",
      zip: 80621,
      phone: 7202305871,
      state_id: 5,
  },
  {
      shop_name: "Corvette Masters",
      address: "601 Denver Ave",
      city: "Maitland",
      shop_state: "Florida",
      zip: 32751,
      phone: 4078313990,
      state_id: 8,
  },
  {
      shop_name: "ss performance auto",
      address: "5760 Progress Rd",
      city: "South Miami",
      shop_state: "Florida",
      zip: 33143,
      phone: 3056689792,
      state_id: 8,
  },
  {
      shop_name: "South Georgia Corvette",
      address: "1396 Dillon Rd",
      city: "Thomasville",
      shop_state: "Georgia",
      zip: 31757,
      phone: 2292264447,
      state_id: 9,
  }
];

const seedShop = () => Shop.bulkCreate(shopData);

module.exports = seedShop;

